name: app
channels:
  - defaults
dependencies:
  - bzip2=1.0.8=h2bbff1b_6
  - ca-certificates=2025.12.2=haa95532_0
  - expat=2.7.4=hd7fb8db_0
  - libexpat=2.7.4=hd7fb8db_0
  - libffi=3.4.4=hd77b12b_1
  - libzlib=1.3.1=h02ab6af_0
  - openssl=3.0.19=hbb43b14_0
  - pip=26.0.1=pyhc872135_0
  - python=3.10.19=h981015d_0
  - setuptools=80.10.2=py310haa95532_0
  - sqlite=3.51.1=hda9a48d_0
  - tk=8.6.15=hf199647_0
  - ucrt=10.0.22621.0=haa95532_0
  - vc=14.3=h2df5915_10
  - vc14_runtime=14.44.35208=h4927774_10
  - vs2015_runtime=14.44.35208=ha6b5a95_10
  - wheel=0.46.3=py310haa95532_0
  - xz=5.6.4=h4754444_1
  - zlib=1.3.1=h02ab6af_0
  - pip:
      - albucore==0.0.24
      - albumentations==2.0.8
      - altair==5.5.0
      - annotated-types==0.7.0
      - anyio==4.12.1
      - astor==0.8.1
      - attrs==25.4.0
      - beautifulsoup4==4.14.3
      - blinker==1.9.0
      - branca==0.8.2
      - cachetools==5.5.2
      - certifi==2026.1.4
      - charset-normalizer==3.4.4
      - click==8.3.1
      - colorama==0.4.6
      - cython==3.2.4
      - decorator==5.2.1
      - exceptiongroup==1.3.1
      - filelock==3.20.2
      - fire==0.7.1
      - folium==0.20.0
      - fonttools==4.61.1
      - fsspec==2025.12.0
      - geographiclib==2.1
      - geopy==2.4.1
      - gitdb==4.0.12
      - gitpython==3.1.46
      - greenlet==3.3.0
      - h11==0.16.0
      - httpcore==1.0.9
      - httpx==0.28.1
      - huggingface-hub==0.36.0
      - idna==3.11
      - imageio==2.37.2
      - jinja2==3.1.6
      - joblib==1.5.3
      - jsonschema==4.26.0
      - jsonschema-specifications==2025.9.1
      - kiwipiepy==0.22.2
      - kiwipiepy-model==0.22.1
      - lazy-loader==0.4
      - lmdb==1.7.5
      - lxml==6.0.2
      - markupsafe==3.0.3
      - mpmath==1.3.0
      - narwhals==2.15.0
      - networkx==3.4.2
      - numpy==2.2.6
      - opencv-contrib-python==4.12.0.88
      - opencv-python==4.11.0.86
      - opencv-python-headless==4.12.0.88
      - opt-einsum==3.3.0
      - packaging==24.2
      - paddleocr==2.10.0
      - paddlepaddle==3.0.0
      - pandas==2.3.3
      - pillow==11.2.1
      - protobuf==6.33.2
      - pyarrow==22.0.0
      - pyclipper==1.4.0
      - pydantic==2.12.5
      - pydantic-core==2.41.5
      - pydeck==0.9.1
      - python-dateutil==2.9.0.post0
      - python-docx==1.2.0
      - pytz==2025.2
      - pyyaml==6.0.3
      - rapidfuzz==3.14.3
      - referencing==0.37.0
      - regex==2025.11.3
      - requests==2.32.5
      - rpds-py==0.30.0
      - safetensors==0.7.0
      - scikit-image==0.25.2
      - scikit-learn==1.7.0
      - scipy==1.15.3
      - sentence-transformers==4.1.0
      - sentencepiece==0.2.0
      - shapely==2.1.2
      - simsimd==6.5.12
      - six==1.17.0
      - smmap==5.0.2
      - soupsieve==2.8.1
      - sqlalchemy==2.0.45
      - sqlmodel==0.0.24
      - streamlit==1.45.1
      - streamlit-folium==0.26.1
      - stringzilla==4.6.0
      - sympy==1.14.0
      - tenacity==9.1.2
      - termcolor==3.3.0
      - threadpoolctl==3.6.0
      - tifffile==2025.5.10
      - timm==1.0.24
      - tokenizers==0.21.4
      - toml==0.10.2
      - torch==2.10.0
      - torchvision==0.25.0
      - tornado==6.5.4
      - tqdm==4.67.1
      - transformers==4.52.4
      - typing-extensions==4.15.0
      - typing-inspection==0.4.2
      - tzdata==2025.3
      - urllib3==2.6.3
      - watchdog==6.0.0
      - xyzservices==2025.11.0
prefix: C:\Users\rkgml\miniconda3\envs\app
